// Tests for the install.mjs cost.js extraction step.
// Verifies that:
//   1. The PURE_FUNCTIONS_BEGIN/END markers exist in auto-sprint.js
//   2. The extracted block can be written as a valid CommonJS module
//   3. All expected exports are present and correctly typed
//   4. The extracted module produces correct output (smoke test of key functions)
//   5. The installer logic itself is exercised (extractCostJs helper)

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import os from 'node:os';
import { tmpdir } from 'node:os';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const AUTO_SPRINT = join(ROOT, '.claude', 'workflows', 'auto-sprint.js');

// Replicate the extraction logic from install.mjs so we can test it directly.
function extractCostJs(src) {
  const blockStart = src.indexOf('// PURE_FUNCTIONS_BEGIN');
  const blockEnd   = src.indexOf('// PURE_FUNCTIONS_END') + '// PURE_FUNCTIONS_END'.length;
  if (blockStart < 0 || blockEnd < blockStart) return null;
  const block = src.slice(blockStart, blockEnd);
  return [
    '// Auto-generated by apra-pm install.mjs -- do not edit directly.',
    '',
    block,
    '',
    'if (typeof module !== \'undefined\') {',
    '  module.exports = {',
    '    DEFAULT_CALIBRATION,',
    '    computeSprintQuote,',
    '    computeSprintAnalysis,',
    '    accumulateBucketTokens,',
    '    computeUpdatedCalibration,',
    '    buildSprintSummary,',
    '    buildExecutionSummary,',
    '    reviewerModelFor,',
    '  };',
    '}',
  ].join('\n');
}

// -- marker presence -----------------------------------------------------------

test('auto-sprint.js has PURE_FUNCTIONS_BEGIN marker', () => {
  const src = readFileSync(AUTO_SPRINT, 'utf-8');
  assert.ok(src.includes('// PURE_FUNCTIONS_BEGIN'),
    'auto-sprint.js must contain // PURE_FUNCTIONS_BEGIN');
});

test('auto-sprint.js has PURE_FUNCTIONS_END marker', () => {
  const src = readFileSync(AUTO_SPRINT, 'utf-8');
  assert.ok(src.includes('// PURE_FUNCTIONS_END'),
    'auto-sprint.js must contain // PURE_FUNCTIONS_END');
});

test('PURE_FUNCTIONS_BEGIN appears before PURE_FUNCTIONS_END', () => {
  const src = readFileSync(AUTO_SPRINT, 'utf-8');
  const start = src.indexOf('// PURE_FUNCTIONS_BEGIN');
  const end   = src.indexOf('// PURE_FUNCTIONS_END');
  assert.ok(start < end, 'BEGIN must precede END');
});

// -- extraction produces valid JS ----------------------------------------------
// Load costMod at module level so failures show the real error, not a cascade of
// "cost.js not loaded" from downstream tests that depend on it.

const _costSrc = readFileSync(AUTO_SPRINT, 'utf-8');
const _costJs  = extractCostJs(_costSrc);
if (!_costJs) throw new Error('extractCostJs returned null -- PURE_FUNCTIONS markers missing in auto-sprint.js');
const _costDir  = join(tmpdir(), 'apra-pm-test-cost-extraction');
mkdirSync(_costDir, { recursive: true });
const _costPath = join(_costDir, 'cost.js');
writeFileSync(_costPath, _costJs);
const _req = createRequire(import.meta.url);
const costMod = _req(_costPath);

test('extractCostJs produces a non-empty string', () => {
  assert.ok(typeof _costJs === 'string' && _costJs.length > 0,
    'extractCostJs must return a non-empty string');
});

test('extracted cost.js is a valid CommonJS module (require succeeds)', () => {
  assert.ok(costMod, 'require() of extracted cost.js must not throw');
});

// -- expected exports are present ----------------------------------------------

test('cost.js exports DEFAULT_CALIBRATION as an object', () => {
  assert.equal(typeof costMod.DEFAULT_CALIBRATION, 'object');
  assert.ok(costMod.DEFAULT_CALIBRATION !== null);
});

test('cost.js DEFAULT_CALIBRATION has schema_version field', () => {
  assert.ok('schema_version' in costMod.DEFAULT_CALIBRATION,
    'DEFAULT_CALIBRATION must have schema_version');
});

test('cost.js exports computeSprintQuote as a function', () => {
  assert.equal(typeof costMod.computeSprintQuote, 'function');
});

test('cost.js exports computeSprintAnalysis as a function', () => {
  assert.equal(typeof costMod.computeSprintAnalysis, 'function');
});

test('cost.js exports computeUpdatedCalibration as a function', () => {
  assert.equal(typeof costMod.computeUpdatedCalibration, 'function');
});

test('cost.js exports buildSprintSummary as a function', () => {
  assert.equal(typeof costMod.buildSprintSummary, 'function');
});

test('cost.js exports accumulateBucketTokens as a function', () => {
  assert.equal(typeof costMod.accumulateBucketTokens, 'function');
});

test('cost.js exports reviewerModelFor as a function', () => {
  assert.equal(typeof costMod.reviewerModelFor, 'function');
});

// -- smoke tests: functions produce correct output when called via require() ---

test('computeSprintQuote via require() returns a valid quote object', () => {
  const { computeSprintQuote, DEFAULT_CALIBRATION } = costMod;
  const q = computeSprintQuote(
    [{ id: 'BD-1', bucket: 'M', model: 'standard' }],
    DEFAULT_CALIBRATION
  );
  assert.ok(q, 'quote must not be null');
  assert.ok(typeof q.scenarios === 'object', 'quote must have scenarios');
  assert.ok(typeof q.scenarios.expected.outputOnly === 'number', 'expected scenario must be a number');
  assert.ok(!isNaN(q.scenarios.expected.outputOnly), 'expected outputOnly must not be NaN');
  assert.ok(q.scenarios.expected.outputOnly > 0, 'expected outputOnly must be positive');
});

test('computeSprintQuote via require() total = outputOnly * inputMultiplier', () => {
  const { computeSprintQuote, DEFAULT_CALIBRATION } = costMod;
  const q = computeSprintQuote(
    [{ id: 'BD-1', bucket: 'M', model: 'standard' }],
    DEFAULT_CALIBRATION
  );
  for (const s of Object.values(q.scenarios)) {
    assert.ok(Math.abs(s.total - s.outputOnly * q.inputMultiplier) < 1e-9,
      'total must equal outputOnly * inputMultiplier');
  }
});

test('reviewerModelFor via require(): premium stays premium', () => {
  assert.equal(costMod.reviewerModelFor('premium'), 'premium');
});

test('reviewerModelFor via require(): cheap escalates to standard', () => {
  assert.equal(costMod.reviewerModelFor('cheap'), 'standard');
});

test('DEFAULT_CALIBRATION via require() has tier-name price keys', () => {
  const prices = costMod.DEFAULT_CALIBRATION.model_prices_per_1m_output_tokens;
  assert.ok('cheap'    in prices, 'prices must have cheap key');
  assert.ok('standard' in prices, 'prices must have standard key');
  assert.ok('premium'  in prices, 'prices must have premium key');
  // Must NOT have provider-specific model ID keys
  for (const key of Object.keys(prices)) {
    if (key === '_doc') continue;
    assert.doesNotMatch(key, /claude-/, `prices key "${key}" must not be a model ID`);
  }
});

test('extractCostJs returns null when markers are absent', () => {
  const result = extractCostJs('// no markers here\nfunction foo() {}');
  assert.equal(result, null);
});
